/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package curso.tecnicas.GUI;

import java.awt.Color;

/**
 *
 * @author Aula 8 - Docente
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEstadoCivil = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        chkSmartphone = new javax.swing.JCheckBox();
        chkNotebook = new javax.swing.JCheckBox();
        chkTablet = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMensajeSalida = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnCargar1 = new javax.swing.JButton();
        rbnCasado = new javax.swing.JRadioButton();
        rbnSoltero = new javax.swing.JRadioButton();
        rbnDivorciado = new javax.swing.JRadioButton();
        rbnViudo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbColores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        chkSmartphone.setText("Smartphone");

        chkNotebook.setText("Notebook");

        chkTablet.setText("Tablet");

        jLabel3.setText("Seleccione, si tiene:");

        txaMensajeSalida.setEditable(false);
        txaMensajeSalida.setColumns(20);
        txaMensajeSalida.setRows(5);
        jScrollPane1.setViewportView(txaMensajeSalida);

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 255));
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 102));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCargar1.setBackground(new java.awt.Color(102, 102, 255));
        btnCargar1.setForeground(new java.awt.Color(0, 0, 102));
        btnCargar1.setText("CARGAR");
        btnCargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar1ActionPerformed(evt);
            }
        });

        grupoEstadoCivil.add(rbnCasado);
        rbnCasado.setText("Casado");
        rbnCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnCasadoActionPerformed(evt);
            }
        });

        grupoEstadoCivil.add(rbnSoltero);
        rbnSoltero.setText("Soltero");

        grupoEstadoCivil.add(rbnDivorciado);
        rbnDivorciado.setText("Divorciado");

        grupoEstadoCivil.add(rbnViudo);
        rbnViudo.setText("Viudo");

        jLabel4.setText("Estado Civil:");

        jLabel5.setText("Seleccione un color:");

        cmbColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Gris", "Naranja", "Purpura", "Rojo", "Rosa", "Verde" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCargar1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(chkSmartphone)
                                            .addComponent(chkTablet))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbnSoltero)
                                                    .addComponent(rbnCasado)
                                                    .addComponent(rbnDivorciado)
                                                    .addComponent(rbnViudo))))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbColores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkNotebook))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSmartphone)
                    .addComponent(rbnCasado)
                    .addComponent(cmbColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkNotebook)
                    .addComponent(rbnSoltero, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTablet)
                    .addComponent(rbnDivorciado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbnViudo)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCargar1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();      
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void limpiarFormulario() {
        txtNombre.setText("");
        txtApellido.setText("");
        txaMensajeSalida.setText("");
        chkSmartphone.setSelected(false);
        chkNotebook.setSelected(false);
        chkTablet.setSelected(false);
        grupoEstadoCivil.clearSelection();
        txtNombre.requestFocus();
        
    }
    
    public void ponerColor(){
        String color = (String) cmbColores.getSelectedItem();
        switch (color){
            case "Azul":
                txaMensajeSalida.setBackground(Color.YELLOW);
                txaMensajeSalida.setForeground(Color.WHITE);break;
            case "Gris":                
                txaMensajeSalida.setBackground(Color.BLUE);
                txaMensajeSalida.setForeground(Color.WHITE);break;
            case "Naranja":
                txaMensajeSalida.setBackground(Color.RED);
                txaMensajeSalida.setForeground(Color.WHITE);break;
            case "Purpura":
                txaMensajeSalida.setBackground(Color.ORANGE);
                txaMensajeSalida.setForeground(Color.WHITE);break;
            case "Rojo":                
                txaMensajeSalida.setBackground(Color.GRAY);
                txaMensajeSalida.setForeground(Color.WHITE);break;
            case "Rosa":
                txaMensajeSalida.setBackground(Color.GREEN);
                txaMensajeSalida.setForeground(Color.WHITE);break;
            case "Verde":
                txaMensajeSalida.setBackground(Color.PINK);
                txaMensajeSalida.setForeground(Color.WHITE);break;
        }
    }
    

    private void btnCargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar1ActionPerformed
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String texto = "Hola "+nombre+" "+apellido+" !!\n";
        if(chkNotebook.isSelected()) texto += "Tiene notebook.\n";
        if(chkSmartphone.isSelected()) texto += "Tiene Smartphone.\n";
        if(chkTablet.isSelected()) texto += "Tiene tablet.\n";    
        if(rbnCasado.isSelected()) texto += "Su estado es "+rbnCasado.getText()+"\n";
        if(rbnSoltero.isSelected()) texto += "Su estado es "+rbnSoltero.getText()+"\n";
        if(rbnDivorciado.isSelected()) texto += "Su estado es "+rbnDivorciado.getText()+"\n";
        if(rbnViudo.isSelected()) texto += "Su estado es "+rbnViudo.getText()+"\n";
        
        ponerColor();
        
        txaMensajeSalida.setText(texto);
    }//GEN-LAST:event_btnCargar1ActionPerformed

    private void rbnCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnCasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnCasadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox chkNotebook;
    private javax.swing.JCheckBox chkSmartphone;
    private javax.swing.JCheckBox chkTablet;
    private javax.swing.JComboBox<String> cmbColores;
    private javax.swing.ButtonGroup grupoEstadoCivil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbnCasado;
    private javax.swing.JRadioButton rbnDivorciado;
    private javax.swing.JRadioButton rbnSoltero;
    private javax.swing.JRadioButton rbnViudo;
    private javax.swing.JTextArea txaMensajeSalida;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
